import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://eventhub.rahulshettyacademy.com/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('tts@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Federal#89');
  await page.getByRole('textbox', { name: 'Password' }).press('Tab');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('heading', { name: 'Discover & Book Amazing Events' }).click();
  await expect(page.getByRole('heading', { name: 'Discover & Book Amazing Events' })).toBeVisible();
  await page.getByTestId('nav-home').click();
  await page.getByRole('button', { name: 'Admin' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Manage Events' }).click();
  await page.getByTestId('event-title-input').click();
  await page.getByTestId('event-title-input').fill('SundayFun Event');
  await page.getByTestId('event-title-input').press('Tab');
  await page.getByRole('textbox', { name: 'Describe the event…' }).fill('Only for sunday event ');
  await page.getByLabel('Category*').selectOption('Festival');
  await page.getByRole('textbox', { name: 'City*' }).click();
  await page.getByRole('textbox', { name: 'City*' }).fill('Delhi');
  await page.getByText('Title*DescriptionOnly for').click();
  await page.getByText('EventHubHomeEventsMy BookingsAPI DocsAdmintts@gmail.comLogout+ New EventYou can').press('ArrowDown');
  await page.getByText('EventHubHomeEventsMy BookingsAPI DocsAdmintts@gmail.comLogout+ New EventYou can').press('ArrowDown');
  await page.getByText('EventHubHomeEventsMy BookingsAPI DocsAdmintts@gmail.comLogout+ New EventYou can').press('ArrowDown');
  await page.getByRole('textbox', { name: 'Venue*' }).click();
  await page.getByRole('textbox', { name: 'Venue*' }).fill('APJ Auditerium');
  await page.getByRole('textbox', { name: 'Event Date & Time*' }).click();
  await page.getByRole('textbox', { name: 'Event Date & Time*' }).fill('2026-10-10T10:00');
  await page.getByRole('spinbutton', { name: 'Price ($)*' }).click();
  await page.getByRole('spinbutton', { name: 'Price ($)*' }).fill('10');
  await page.getByRole('spinbutton', { name: 'Total Seats*' }).click();
  await page.getByRole('spinbutton', { name: 'Total Seats*' }).fill('20');
  await page.getByRole('textbox', { name: 'Event Date & Time*' }).click();
  await page.getByRole('textbox', { name: 'Image URL (optional)' }).click();
  await page.getByRole('textbox', { name: 'Image URL (optional)' }).fill('https://www.api.com');
  await page.getByTestId('add-event-btn').click();
});